model:
  name: "google/siglip-base-patch16-224"
  type: "siglip"

optimizer:
  lr: 5.0e-5 
  weight_decay: 0.1

training:
  loss_type: "sigmoid"
  mini_batch_size: 128
  gradient_accumulation_steps: 256